### ISSUE TITLE
Script error  client 64 no such export addboxzone in resource ox target 

### ISSUE THREAD

**Issue by CapitalCreator** [Muhaddil/muhaddil_insurance#1]
![image](https://github.com/user-attachments/assets/53060d1f-f478-4a29-b688-0ffa204226e2)         can you not use qb target ?

**Comment by Muhaddil** [comment]
Fixed in the latest update!

 [v1.0.6](https://github.com/Muhaddil/muhaddil_insurance/releases/tag/v1.0.6)
 
 And sorry for the late response.
